services:
  - type: web
    name: spring-boot-backend
    runtime: docker
    plan: starter
    region: frankfurt
    autoDeploy: false

    dockerfilePath: ./Dockerfile

    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
