services:
  - type: web
    name: spring-boot-backend
    env: java
    plan: starter
    region: frankfurt
    autoDeploy: false

    buildCommand: ./gradlew clean build -x test
    startCommand: java -jar build/libs/*.jar

    envVars:
      - key: JAVA_VERSION
        value: 17
      - key: SPRING_PROFILES_ACTIVE
        value: prod
